### ISSUE TITLE
I can't get ExtractedArtifactStore to behave

### ISSUE THREAD

**Issue by kpagratis** [flapdoodle-oss/de.flapdoodle.embed.process#115]
I'm creating an ExtractedArtifactStore like so
```
val extractDir = DirectoryAndExecutableNaming
      .builder()
      .directory(new UserHome(".cached/extracted"))
      .executableNaming(Defaults.executableNaming())
      .build()

    val tempDir = DirectoryAndExecutableNaming
      .builder()
      .directory(new UserHome(".cached/extracted/temp"))
      .executableNaming(Defaults.executableNaming())
      .build()

    val store = ExtractedArtifactStore
      .builder()
      .downloader(Downloader.platformDefault())
      .downloadConfig(downloadConfig)
      .extraction(extractDir)
      .temp(tempDir)
      .build()
```

My package resolver is defined with the following fileset
```
       FileSet
              .builder()
              .addEntry(FileType.Executable, "bin/mysqld")
              .addEntry(FileType.Library, "bin/mysql")
              .addEntry(FileType.Library, "share/english/errmsg.sys")
              .build()
```

When calling prepare on my starter, I get the following exception 

```
2021-01-25 18:38:12,594  ERROR: d.f.e.p.r.Starter         prepare executable
java.nio.file.NoSuchFileException: /Users/kpagratis/.cached/extracted/temp/extract-794650b2-7afe-4531-82fb-4b965422dc6emysqld
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:243)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at de.flapdoodle.embed.process.extract.ExtractedFileSets.copy(ExtractedFileSets.java:53)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:114)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:58)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:51)
	at <redacted>.A$.main(SomeExecutable.scala:150)
	at <redacted>.A.main(SomeExecutable.scala)
Exception in thread "main" de.flapdoodle.embed.process.exceptions.DistributionException: java.nio.file.NoSuchFileException: /Users/kpagratis/.cached/temp/extract-794650b2-7afe-4531-82fb-4b965422dc6emysqld
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:70)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:51)
	at <redacted>.A$.main(SomeExecutable.scala:150)
	at <redacted>.A.main(SomeExecutable.scala)
Caused by: java.nio.file.NoSuchFileException: /Users/kpagratis/.cached/extracted/temp/extract-794650b2-7afe-4531-82fb-4b965422dc6emysqld
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:243)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at de.flapdoodle.embed.process.extract.ExtractedFileSets.copy(ExtractedFileSets.java:53)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:114)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:58)
	... 3 more
```

And my extracted looks like so 
```
.
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64/8.0.21
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64/8.0.21/mysql-8.0.21-macos10.15-x86_64-8.0.21.tar.gz
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64/8.0.21/mysql-8.0.21-macos10.15-x86_64-8.0.21.tar.gz/extract-fd9cdf37-5b3f-4a8a-be3b-17f42a2228bdbin
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64/8.0.21/mysql-8.0.21-macos10.15-x86_64-8.0.21.tar.gz/extract-fd9cdf37-5b3f-4a8a-be3b-17f42a2228bdbin/mysqld
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64/8.0.21/mysql-8.0.21-macos10.15-x86_64-8.0.21.tar.gz/bin
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64/8.0.21/mysql-8.0.21-macos10.15-x86_64-8.0.21.tar.gz/bin/mysql
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64/8.0.21/mysql-8.0.21-macos10.15-x86_64-8.0.21.tar.gz/share
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64/8.0.21/mysql-8.0.21-macos10.15-x86_64-8.0.21.tar.gz/share/english
./OS_X-B64--mysql-8.0.21-macos10.15-x86_64/8.0.21/mysql-8.0.21-macos10.15-x86_64-8.0.21.tar.gz/share/english/errmsg.sys
```

Any help would be greatly appreciated. Thanks!

**Comment by kpagratis** [comment]
I've also tried
```
    val extractDir = DirectoryAndExecutableNaming
      .builder()
      .directory(new UserHome(".cached/extracted"))
      .executableNaming((_: String, postfix: String) => postfix)
      .build()

    val tempDir = DirectoryAndExecutableNaming
      .builder()
      .directory(new UserHome(".cached/extracted/temp"))
      .executableNaming((_: String, postfix: String) => postfix)
      .build()

    val store = ExtractedArtifactStore
      .builder()
      .downloader(Downloader.platformDefault())
      .downloadConfig(downloadConfig)
      .extraction(extractDir)
      .temp(tempDir)
      .build()
    store
  }

```

The extracted directory looks fine but it fails with 
```
Caused by: java.nio.file.NoSuchFileException: /Users/kpagratis/.cached/extracted/temp/mysqld
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copyFile(UnixCopyFile.java:243)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:581)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at de.flapdoodle.embed.process.extract.ExtractedFileSets.copy(ExtractedFileSets.java:53)
	at de.flapdoodle.embed.process.store.ExtractedArtifactStore.extractFileSet(ExtractedArtifactStore.java:114)
	at de.flapdoodle.embed.process.runtime.Starter.prepare(Starter.java:58)
```

The strange this is this fails the first time, then runs as expected after that.

**Comment by kpagratis** [comment]
This code is written in scala and is running against version 3.0.1

**Comment by kpagratis** [comment]
I ended up creating my own store that doesn't munge the executable name

**Comment by michaelmosmann** [comment]
hmm.. i would guess, that it fails because at first the directory is missing.. but it just a guess...

**Comment by michaelmosmann** [comment]
as there are new releases and a big refactoring ahead i close this issue.. reopen if still a problem.
