### ISSUE TITLE
process is null in GitLab CI running gradle check / test

### ISSUE THREAD

**Issue by ImpulseTheFox** [flapdoodle-oss/de.flapdoodle.embed.process#132]
```
Caused by:
                    org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoTemplate' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryDependentConfiguration.class]: Unsatisfied dependency expressed through method 'mongoTemplate' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "de.flapdoodle.embed.process.runtime.ProcessControl.getPid()" because "this.process" is null
                        at app//org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
                        at app//org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
                        at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
                        at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
                        at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
                        at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
                        at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
                        at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                        at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
                        at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
                        at app//org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:330)
                        ... 124 more
                        Caused by:
                        org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'mongoDatabaseFactory' defined in class path resource [org/springframework/boot/autoconfigure/data/mongo/MongoDatabaseFactoryConfiguration.class]: Unsatisfied dependency expressed through method 'mongoDatabaseFactory' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "de.flapdoodle.embed.process.runtime.ProcessControl.getPid()" because "this.process" is null
                            at app//org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
                            at app//org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
                            at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
                            at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
                            at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
                            at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
                            at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
                            at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                            at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
                            at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
                            at app//org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
                            at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
                            at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
                            at app//org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
                            at app//org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
                            ... 134 more
                            Caused by:
                            org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedMongoServer' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke "de.flapdoodle.embed.process.runtime.ProcessControl.getPid()" because "this.process" is null
                                at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
                                at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
                                at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
                                at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
                                at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
                                at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
                                at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
                                at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
                                at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
                                at app//org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
                                at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1389)
                                at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
                                at app//org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
                                at app//org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
                                ... 148 more
                                Caused by:
                                java.lang.NullPointerException: Cannot invoke "de.flapdoodle.embed.process.runtime.ProcessControl.getPid()" because "this.process" is null
                                    at de.flapdoodle.embed.process.runtime.AbstractProcess.getProcessId(AbstractProcess.java:229)
                                    at de.flapdoodle.embed.process.runtime.AbstractProcess.sendKillToProcess(AbstractProcess.java:210)
                                    at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:109)
                                    at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:174)
                                    at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:118)
                                    at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
                                    at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
                                    at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
                                    at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
                                    at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:109)
                                    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                                    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                                    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1930)
                                    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1872)
                                    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
                                    ... 161 more
```

**Comment by michaelmosmann** [comment]
@ImpulseTheFox which version of de.flapdoodle.embed.mongo do you use?

**Comment by ImpulseTheFox** [comment]
I did not specify a version in the gradle build file, so I'm not sure. However the property spring.mongodb.embedded.version in the application.yml is 3.5.5Am 21.05.2022 08:43 schrieb Michael Mosmann ***@***.***>:
@ImpulseTheFox which version of de.flapdoodle.embed.mongo do you use?

**Comment by michaelmosmann** [comment]
@ImpulseTheFox ok..so which spring version do you use?

**Comment by Wawrzyniec-Nowak** [comment]
I got the same problem without using spring. Version of the lib 3.1.4 but it looks like it exists on main branch because if the exception happens before https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/runtime/AbstractProcess.java#L98 the process is null and during stop() it may call https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/55fde02b3681548cf770b3a40a59d76b5b65d339/src/main/java/de/flapdoodle/embed/process/runtime/AbstractProcess.java#L215 which tries to get pid of the process (which is null). Here is a stacktrace I got
`java.lang.NullPointerException
at de.flapdoodle.embed.process.runtime.AbstractProcess.getProcessId(AbstractProcess.java:229)
at de.flapdoodle.embed.process.runtime.AbstractProcess.sendKillToProcess(AbstractProcess.java:210)
at de.flapdoodle.embed.mongo.AbstractMongoProcess.stopInternal(AbstractMongoProcess.java:111)
at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:174)
at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:118)
at de.flapdoodle.embed.mongo.AbstractMongoProcess.<init>(AbstractMongoProcess.java:53)
at de.flapdoodle.embed.mongo.MongodProcess.<init>(MongodProcess.java:50)
at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:44)
at de.flapdoodle.embed.mongo.MongodExecutable.start(MongodExecutable.java:34)
at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:109)`

**Comment by michaelmosmann** [comment]
@Wawrzyniec-Nowak ah.. will have a look

**Comment by stefanbethke** [comment]
The NPE is a secondary problem that occurs when the `mongod` binary cannot be run. In our case, the problem is that the Alpine-based image we're using in our pipeline does not have the library dependencies that `mongod` requires. There should be a stack trace above that shows the failure to execute the binary.

**Comment by michaelmosmann** [comment]
Reopen if needed..
