### ISSUE TITLE
ContentHashExtractedFileSetStore fails with embeddedmongo when ~/.embedmongo does not exist

### ISSUE THREAD

**Issue by froth** [flapdoodle-oss/de.flapdoodle.embed.process#136]
mondod.start fails when ~/.embededmongo does not exist, works fine if it does.

```Caused by: java.nio.file.NoSuchFileException: /home/me/.embedmongo/fileSets
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:397)
	at java.base/java.nio.file.Files.createDirectory(Files.java:700)
	at de.flapdoodle.embed.process.store.ContentHashExtractedFileSetStore.lambda$new$0(ContentHashExtractedFileSetStore.java:50)
	at de.flapdoodle.types.ThrowingRunnable.lambda$mapCheckedException$0(ThrowingRunnable.java:27)```


I believe the problem is here (and maybe on other calls of `java.nio.file.Files.createDirectory`), because createDirectory does not create parent dirs. I think createDirectories should work, but I haven't read all the code so maybe the problem is somewhere else.

https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/main/src/main/java/de/flapdoodle/embed/process/store/ContentHashExtractedFileSetStore.java#L50

**Comment by michaelmosmann** [comment]
@froth did a new release where this bug is fixed (4.1.2)
