### ISSUE TITLE
JDK 20: java.lang.NoSuchFieldException: handle => Wrong PID helper?

### ISSUE THREAD

**Issue by jerboaa** [flapdoodle-oss/de.flapdoodle.embed.process#137]
We see a failure in some quarkus native integration tests which uses flapdoodle for process interaction. The JDK 20 build fails with:

```
 java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2707)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:111)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:45)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$3.getPid(Processes.java:242)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:80)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:61)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:177)
	at de.flapdoodle.embed.process.types.RunningProcess.start(RunningProcess.java:71)
	at de.flapdoodle.embed.mongo.transitions.MongoServerStarter.result(MongoServerStarter.java:119)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:62)
	at de.flapdoodle.reverse.TransitionWalker.resolve(TransitionWalker.java:50)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:165)
	at de.flapdoodle.reverse.TransitionWalker.initState(TransitionWalker.java:69)
	at de.flapdoodle.embed.mongo.transitions.Mongod.start(Mongod.java:90)
	at io.quarkus.test.mongodb.MongoTestResource.start(MongoTestResource.java:71)
	at io.quarkus.test.common.TestResourceManager$TestResourceEntryRunnable.run(TestResourceManager.java:481)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1591)
```

It looks to me that it's not detecting the JDK version correctly and using the `LEGACY` pid helper here:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/main/src/main/java/de/flapdoodle/embed/process/runtime/Processes.java#L237 while it should be using the JDK 11 one (`java.lang.Process.pid()` exists in JDK 20).

**Comment by michaelmosmann** [comment]
@jerboaa yes.. i should change this... so legacy is only used if we know for sure..

**Comment by michaelmosmann** [comment]
@jerboaa .. there is a new release ahead 4.4.1 which should solve this issue.. will be in maven central in 12-24hrs from now.. (i guess)

**Comment by jerboaa** [comment]
Thanks for the quick turn-around!

**Comment by michaelmosmann** [comment]
@jerboaa was easy:)

**Comment by zakkak** [comment]
FTR fixed by https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/commit/a3eeab48482b903445098e0f5fe65e7803d29228

Thanks @michaelmosmann
