### ISSUE TITLE
OutOfMemoryError in LogWatchStreamProcessor when running many commands

### ISSUE THREAD

**Issue by danielFesenmeyerAtBosch** [flapdoodle-oss/de.flapdoodle.embed.process#27]
When running many commands (e.g. 100.000 inserts with the async Mongo Java driver), an OutOfMemoryError occurs:

Exception in thread "Thread-4" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Unknown Source)
	at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at java.lang.AbstractStringBuilder.append(Unknown Source)
	at java.lang.StringBuilder.append(Unknown Source)
	at de.flapdoodle.embed.process.io.LogWatchStreamProcessor.process(LogWatchStreamProcessor.java:52)
	at de.flapdoodle.embed.process.io.ReaderProcessor.run(ReaderProcessor.java:52)

**Comment by danielFesenmeyerAtBosch** [comment]
Moved this issue to de.flapdoodle.embed.mongo.
