### ISSUE TITLE
Allow control of cleanup timing

### ISSUE THREAD

**Issue by benson-basis** [flapdoodle-oss/de.flapdoodle.embed.process#36]
This library sets shutdown hooks. This can lead to some very strange class loading problems in Maven 3.2.x and above, as shown below. As best I can work out, the only fix here is to expose an API to allow a maven plugin that is calling this library (or a library that calls this library, like the mongo embedded) to explicitly shut things down when it's done.

```
Exception in thread "Thread-6" java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
    at de.flapdoodle.embed.process.io.file.Files.forceDelete(Files.java:104)
    at de.flapdoodle.embed.process.runtime.AbstractProcess.stop(AbstractProcess.java:168)
    at de.flapdoodle.embed.process.runtime.Executable.stop(Executable.java:71)
    at de.flapdoodle.embed.process.runtime.Executable$JobKiller.run(Executable.java:88)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
```

**Comment by ispringer** [comment]
Any chance you can do a release that includes this fix?
