### ISSUE TITLE
java.lang.NoSuchFieldException: handle error on Linux

### ISSUE THREAD

**Issue by sdeleuze** [flapdoodle-oss/de.flapdoodle.embed.process#79]
This prints a stacktrace on Linux and IMO should be avoided: https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/blob/master/src/main/java/de/flapdoodle/embed/process/runtime/Processes.java#L120

```
java.lang.NoSuchFieldException: handle
	at java.base/java.lang.Class.getDeclaredField(Class.java:2370)
	at de.flapdoodle.embed.process.runtime.Processes.windowsProcessId(Processes.java:109)
	at de.flapdoodle.embed.process.runtime.Processes.access$200(Processes.java:51)
	at de.flapdoodle.embed.process.runtime.Processes$PidHelper$2.getPid(Processes.java:209)
	at de.flapdoodle.embed.process.runtime.Processes.processId(Processes.java:72)
	at de.flapdoodle.embed.process.runtime.ProcessControl.<init>(ProcessControl.java:64)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:99)
```

**Comment by Loki-Afro** [comment]
duplicate .. https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/issues/78
